#FROM postgres:9.5
#EXPOSE 5432
#ADD create_db.sql /docker-entrypoint-initdb.d/

#FROM postgres:10.12

#ENV POSTGRES_USER postgres
#ENV POSTGRES_PASSWORD root
#ENV POSTGRES_DB schedule

#ADD create_db.sql /docker-entrypoint-initdb.d/