spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/schedule}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:root}
    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
      max-lifetime: 1800000
      data-source-properties:
        prepareThreshold: 1
        preparedStatementCacheQueries: 256
        preparedStatementCacheSizeMiB: 5

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: ${LIQUIBASE_ENABLED:true}

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:dummy}
            client-secret: ${GOOGLE_CLIENT_SECRET:dummy}
          facebook:
            client-id: ${FACEBOOK_CLIENT_ID:dummy}
            client-secret: ${FACEBOOK_CLIENT_SECRET:dummy}

  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://127.0.0.1:27017/schedules}
      database: ${MONGO_DB:schedules}

  mail:
    host: ${MAIL_HOST:smtp-relay.brevo.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:a3f2a9001@smtp-brevo.com}
    password: ${MAIL_PASSWORD:xsmtpsib-26998c1d3ade59913f02ddd84ee3c6bf486f4e60f1869dafbab6601e492a1472-4LvYVjbaXVctCc82}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

#  mail:
#    host: ${MAIL_HOST:smtp-relay.brevo.com}
#    port: ${MAIL_PORT:587}
#    username: ${MAIL_USERNAME:a335c2001@smtp-brevo.com}
#    password: ${MAIL_PASSWORD:xsmtpsib-fbcd5f641956f72952457a80fce80b2ecd4b581aa3251a441fdf2cdb626d6d97-JQ4QkLdftfHXmpZG}
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true

openapi:
  server-url: https://fmi-schedule.chnu.edu.ua

# Hibernate
hibernate:
  dialect: org.hibernate.dialect.PostgreSQLDialect
  show_sql: ${HIBERNATE_SHOW_SQL:false}
  hbm2ddl:
    auto: validate
  entity:
    package: com.softserve.entity

# Application
app:
  jwt:
    token:
      secret: ${JWT_SECRET:jwttoken}
      expired: ${JWT_EXPIRED:24h}
  frontend:
    url: ${FRONTEND_URL:https://fmi-schedule.chnu.edu.ua/}
  backend:
    url: ${BACKEND_URL:https://fmi-schedule.chnu.edu.ua/}
  cors:
    allowed-origins: ${CORS_ORIGINS:http://localhost:3000}


  mail:
    #    sender: ${MAIL_SENDER:nromanen.softserveinc@gmail.com}
    sender: ${MAIL_SENDER:fmi-schedule@proton.me}
    enabled: ${MAIL_ENABLED:true}

# Redis
redis:
  address: ${REDIS_URL:redis://127.0.0.1:6379}

# Server
server:
  port: ${PORT:8080}
  servlet:
    context-path: ${CONTEXT_PATH:/}

# Logging
logging:
  level:
    com.softserve: WARN
    org.hibernate.SQL: ${SQL_LOG_LEVEL:WARN}
    org.springframework.security: WARN

#logging:
#  level:
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type.descriptor.sql: TRACE