export const links = {
    HOME_PAGE: '/',
    ADMIN_PAGE: '/admin',
    SCHEDULE_PAGE: '/schedules',
    LOGIN: '/login',
    ACTIVATION_PAGE: '/activation-page',
    LOGOUT: '/logout',
    WISHES: '/wishes',
    TEACHER_SCHEDULE: '/teacher-schedule',
    MY_PROFILE: '/my-profile',
    LessonPage: "/lessons",
    TeacherList: "/teachers",
    GroupList: "/groups",
    ClassScheduleTitle: "/bells",
    RoomList: "/rooms",
    SubjectPage: "/subjects",
    BusyRooms: "/busy-rooms",
    SemesterPage: "/semesters",
    MergeRolePage: "/users",
    Changes: "/changes",
    ScheduleFor:"/schedule",
    Registration:"/registration",
    RESET_PASSWORD:"/reset-password",
    DEPARTMENT_PAGE:"/departments"

};
