const links = {
    HOME_PAGE: '/',
    ADMIN_PAGE: '/admin',
    SCHEDULE_PAGE: '/admin/schedules',
    LOGIN: '/login',
    ACTIVATION_PAGE: '/activation-page',
    LOGOUT: '/logout',
    TEACHER_SCHEDULE: '/teacher-schedule',
    MY_PROFILE: '/my-profile',
    LessonPage: '/admin/lessons',
    TeacherList: '/admin/teachers',
    GroupList: '/admin/groups',
    Group: '/admin/group',
    Student: '/admin/student',
    Edit: '/edit',
    Delete: '/delete',
    AddStudent: '/add-student',
    SetDisable: '/set-disable',
    ShowStudents: '/admin/show-students',
    IdParam: '/:id',
    IdStudentParam: '/:idStudent',
    ClassScheduleTitle: '/admin/period',
    RoomList: '/admin/rooms',
    SubjectPage: '/admin/subjects',
    BusyRooms: '/admin/busy-rooms',
    SemesterPage: '/admin/semesters',
    MergeRolePage: '/admin/users',
    Changes: '/admin/changes',
    ScheduleFor: '/schedule',
    Registration: '/registration',
    RESET_PASSWORD: '/reset-password',
    Departments: '/admin/departments',
};

export { links };
