export const navigationNames = {
    TEACHER_LIST: 'teachers',
    GROUP_LIST: 'groups',
    CLASS_SCHEDULE_TITLE: 'period',
    ROOM_LIST: 'rooms',
    SUBJECT_PAGE: 'subjects',
    SEMESTER_PAGE: 'semesters',
    DEPARTMENTS: 'departments',
    LESSON_PAGE: 'lessons',
    MERGE_ROLE_PAGE: 'users',
    CHANGES: 'changes',
    SCHEDULE_PAGE: 'schedules',
    BUSY_ROOMS: 'busy-rooms',
    TEACHER_LESSONS: 'teacher-lessons',
};