export const navigation = {
    LESSONS: 0,
    USERS: 1,
    CHANGES: 2,
    BUSY_ROOMS: 3,
    PERIOD: 4,
    DEPARTMENTS: 5,
    GROUPS: 6,
    ROOMS: 7,
    SUBJECTS: 8,
    SEMESTERS: 9,
    TEACHERS: 10,
};
export const navigationNames = {
    TEACHER_LIST: 'teachers',
    GROUP_LIST: 'groups',
    CLASS_SCHEDULE_TITLE: 'period',
    ROOM_LIST: 'rooms',
    SUBJECT_PAGE: 'subjects',
    SEMESTER_PAGE: 'semesters',
    DEPARTMENTS: 'departments',
    LESSON_PAGE: 'lessons',
    MERGE_ROLE_PAGE: 'users',
    CHANGES: 'changes',
    BUSY_ROOMS: 'busy-rooms',
};
