// Auth
export const AUTH_USER = 'AUTH_USER';
export const AUTH_USER_SUCCESS = 'AUTH_USER_SUCCESS';
export const AUTH_USER_ERROR = 'AUTH_USER_ERROR';
export const AUTH_USER_INITIATE_LOGOUT = 'AUTH_USER_INITIATE_LOGOUT';
export const AUTH_USER_LOGOUT = 'AUTH_USER_LOGOUT';
export const AUTH_USER_AUTO_LOGOUT = 'AUTH_USER_AUTO_LOGOUT';
export const AUTH_USER_CHECK_STATE = 'AUTH_USER_CHECK_STATE';
export const SET_AUTH_ERROR = 'SET_AUTH_ERROR';
export const SET_AUTH_LOADING_INDICATOR = 'SET_AUTH_LOADING_INDICATOR';

// Registration & Password
export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR';
export const RESET_USER_PASSWORD = 'RESET_USER_PASSWORD';
export const RESET_USER_PASSWORD_SUCCESS = 'RESET_USER_PASSWORD_SUCCESS';
export const RESET_USER_PASSWORD_ERROR = 'RESET_USER_PASSWORD_ERROR';
export const ACTIVATE_USER = 'ACTIVATE_USER';
export const ACTIVATE_USER_SUCCESS = 'ACTIVATE_USER_SUCCESS';
export const ACTIVATE_USER_ERROR = 'ACTIVATE_USER_ERROR';

// Users
export const SET_USERS = 'SET_USERS';
export const SET_USER = 'SET_USER';

// Teachers
export const ADD_TEACHER_START = 'ADD_TEACHER_START';
export const ADD_TEACHER_SUCCESS = 'ADD_TEACHER_SUCCESS';
export const HANDLE_TEACHER_START = 'HANDLE_TEACHER_START';
export const UPDATE_TEACHER_START = 'UPDATE_TEACHER_START';
export const UPDATE_TEACHER_SUCCESS = 'UPDATE_TEACHER_SUCCESS';
export const DELETE_TEACHER_START = 'DELETE_TEACHER_START';
export const DELETE_TEACHER_SUCCESS = 'DELETE_TEACHER_SUCCESS';
export const SHOW_ALL_TEACHERS_START = 'SHOW_ALL_TEACHERS_START';
export const SHOW_ALL_TEACHERS_SUCCESS = 'SHOW_ALL_TEACHERS_SUCCESS';
export const SET_DISABLED_TEACHERS_START = 'SET_DISABLED_TEACHERS_START';
export const SET_DISABLED_TEACHERS_SUCCESS = 'SET_DISABLED_TEACHERS_SUCCESS';
export const GET_TEACHERS_WITH_EMAIL_START = 'GET_TEACHERS_WITH_EMAIL_START';
export const GET_TEACHERS_WITH_EMAIL_SUCCESS = 'GET_TEACHERS_WITH_EMAIL_SUCCESS';
export const GET_TEACHERS_BY_DEPARTMENT = 'GET_TEACHERS_BY_DEPARTMENT';
export const GET_ALL_PUBLIC_TEACHERS_START = 'GET_ALL_PUBLIC_TEACHERS_START';
export const GET_ALL_PUBLIC_TEACHERS_BY_DEPARTMENT_START = 'GET_ALL_PUBLIC_TEACHERS_BY_DEPARTMENT_START';
export const TOOGLE_TEACHER_START = 'TOOGLE_TEACHER_START';
export const SELECT_TEACHER = 'SELECT_TEACHER';
export const SET_TEACHER = 'SET_TEACHER';
export const SELECT_TEACHER_ID = 'SELECT_TEACHER_ID';
export const SET_TEACHER_VIEW_TYPE = 'SET_TEACHER_VIEW_TYPE';

// Groups
export const SHOW_ALL_GROUPS_SUCCESS = 'SHOW_ALL_GROUPS_SUCCESS';
export const SELECT_GROUP_SUCCESS = 'SELECT_GROUP_SUCCESS';
export const SELECT_GROUP_ID = 'SELECT_GROUP_ID';
export const GET_GROUPS_FOR_CURRENT_SEMESTER_START = 'GET_GROUPS_FOR_CURRENT_SEMESTER_START';

// Students
export const SHOW_ALL_STUDENTS = 'SHOW_ALL_STUDENTS';
export const SHOW_ALL_STUDENTS_BY_GROUP_ID = 'SHOW_ALL_STUDENTS_BY_GROUP_ID';
export const CREATE_STUDENT = 'CREATE_STUDENT';
export const CREATE_STUDENT_START = 'CREATE_STUDENT_START';
export const UPDATE_STUDENT = 'UPDATE_STUDENT';
export const UPDATE_STUDENT_START = 'UPDATE_STUDENT_START';
export const DELETE_STUDENT = 'DELETE_STUDENT';
export const DELETE_STUDENT_START = 'DELETE_STUDENT_START';
export const DELETE_SELECTED_STUDENTS = 'DELETE_SELECTED_STUDENTS';
export const SET_STUDENT = 'SET_STUDENT';
export const GET_ALL_STUDENTS = 'GET_ALL_STUDENTS';
export const CHECK_ALL_STUDENTS = 'CHECK_ALL_STUDENTS';
export const MOVE_STUDENTS_TO_GROUP_START = 'MOVE_STUDENTS_TO_GROUP_START';
export const UPLOAD_FILE_STUDENT_START = 'UPLOAD_FILE_STUDENT_START';
export const SUBMIT_STUDENT_FORM = 'SUBMIT_STUDENT_FORM';
export const SET_STUDENTS_LOADING_INDICATOR = 'SET_STUDENTS_LOADING_INDICATOR';

// Rooms
export const ADD_ROOM = 'ADD_ROOM';
export const ADD_ROOM_START = 'ADD_ROOM_START';
export const UPDATE_ROOM = 'UPDATE_ROOM';
export const UPDATE_ROOM_START = 'UPDATE_ROOM_START';
export const DELETE_ROOM = 'DELETE_ROOM';
export const DELETE_ROOM_START = 'DELETE_ROOM_START';
export const SHOW_LIST_OF_ROOMS_SUCCESS = 'SHOW_LIST_OF_ROOMS_SUCCESS';
export const GET_LIST_OF_ROOMS_START = 'GET_LIST_OF_ROOMS_START';
export const GET_LIST_OF_DISABLED_ROOMS_START = 'GET_LIST_OF_DISABLED_ROOMS_START';
export const SET_SELECT_ROOM = 'SET_SELECT_ROOM';
export const CLEAR_ROOM = 'CLEAR_ROOM';
export const SET_DISABLED_ROOMS = 'SET_DISABLED_ROOMS';
export const GET_FREE_ROOMS_START = 'GET_FREE_ROOMS_START';
export const GET_FREE_ROOMS_SUCCESS = 'GET_FREE_ROOMS_SUCCESS';
export const CLEAR_FREE_ROOMS = 'CLEAR_FREE_ROOMS';
export const HANDLE_ROOM_FORM_SUBMIT_START = 'HANDLE_ROOM_FORM_SUBMIT_START';
export const TOGGLE_ROOM_VISIBILITY_START = 'TOGGLE_ROOM_VISIBILITY_START';
export const DRAG_AND_DROP_ROOM_START = 'DRAG_AND_DROP_ROOM_START';
export const UPDATE_ROOM_ORDER_SUCCESS = 'UPDATE_ROOM_ORDER_SUCCESS';
export const SET_ROOMS_LOADING_INDICATOR = 'SET_ROOMS_LOADING_INDICATOR';
export const GET_BUSY_ROOMS_START = 'GET_BUSY_ROOMS_START';
export const GET_BUSY_ROOMS_SUCCESS = 'GET_BUSY_ROOMS_SUCCESS';

// Room Types
export const GET_ALL_ROOM_TYPES = 'GET_ALL_ROOM_TYPES';
export const GET_ALL_ROOM_TYPES_START = 'GET_ALL_ROOM_TYPES_START';
export const ADD_ROOM_TYPE = 'ADD_ROOM_TYPE';
export const UPDATE_ROOM_TYPE = 'UPDATE_ROOM_TYPE';
export const DELETE_ROOM_TYPE = 'DELETE_ROOM_TYPE';
export const DELETE_ROOM_TYPE_START = 'DELETE_ROOM_TYPE_START';
export const SELECT_ROOM_TYPE = 'SELECT_ROOM_TYPE';
export const CLEAR_ONE_NEW_TYPE = 'CLEAR_ONE_NEW_TYPE';
export const HANDLE_ROOM_TYPE_FORM_SUBMIT_START = 'HANDLE_ROOM_TYPE_FORM_SUBMIT_START';

// Subjects
export const SHOW_ALL_SUBJECTS = 'SHOW_ALL_SUBJECT';
export const SELECT_SUBJECT = 'SELECT_SUBJECT';

// Departments
export const GET_ALL_DEPARTMENTS = 'GET_ALL_DEPARTMENTS';
export const GET_DEPARTMENT_BY_ID = 'GET_DEPARTMENT_BY_ID';
export const CLEAR_DEPARTMENT_FORM = 'CLEAR_DEPARTMENT_FORM';

// Semesters
export const ADD_SEMESTER_START = 'ADD_SEMESTER_START';
export const ADD_SEMESTER_SUCCESS = 'ADD_SEMESTER_SUCCESS';
export const UPDATE_SEMESTER_START = 'UPDATE_SEMESTER_START';
export const UPDATE_SEMESTER_SUCCESS = 'UPDATE_SEMESTER_SUCCESS';
export const UPDATE_SEMESTER_BY_ID_START_SUCCESS = 'UPDATE_SEMESTER_BY_ID_START_SUCCESS';
export const DELETE_SEMESTER_START = 'DELETE_SEMESTER_START';
export const DELETE_SEMESTER_SUCCESS = 'DELETE_SEMESTER_SUCCESS';
export const SHOW_ALL_SEMESTERS_SUCCESS = 'SHOW_ALL_SEMESTER';
export const GET_ALL_SEMESTERS_START = 'GET_ALL_SEMESTER_START';
export const SELECT_SEMESTER_SUCCESS = 'SELECT_SEMESTER_SUCCESS';
export const HANDLE_SEMESTER_FORM_SUBMIT_START = 'HANDLE_SEMESTER_FORM_SUBMIT_START';
export const SET_SEMESTER_COPY_START = 'SEMESTER_COPY_START';
export const COPY_LESSONS_FROM_SEMESTER_START = 'COPY_LESSONS_FROM_SEMESTER_START';
export const CLEAR_SEMESTER_SUCCESS = 'CLEAR_SEMESTER_SUCCESS';
export const SET_DISABLED_SEMESTERS_SUCCESS = 'SET_DISABLED_SEMESTERS_SUCCESS';
export const GET_DISABLED_SEMESTERS_START = 'GET_DISABLED_SEMESTERS_START';
export const SET_ARCHIVED_SEMESTERS_START = 'SET_ARCHIVED_SEMESTERS_START';
export const SET_ARCHIVED_SEMESTERS_SUCCESS = 'SET_ARCHIVED_SEMESTERS_SUCCESS';
export const GET_ARCHIVE_SEMESTER_BY_ID_START = 'GET_ARCHIVE_SEMESTER_BY_ID_START';
export const CREATE_ARCHIVE_SEMESTER_START = 'CREATE_ARCHIVE_SEMESTER_START';
export const SET_GROUPS_TO_SEMESTER_START = 'SET_GROUPS_TO_SEMESTER_START';
export const TOGGLE_SEMESTER_VISIBILITY_START = 'TOGGLE_SEMESTER_VISIBILITY_START';
export const MOVE_SEMESTER_TO_ARCHIVE_SUCCESS = 'MOVE_SEMESTER_TO_ARCHIVE_SUCCESS';
export const SET_SEMESTER_LOADING_INDICATOR = 'SET_SEMESTER_LOADING_INDICATOR';

// Lessons
export const CREATE_LESSON_CARD_START = 'CREATE_LESSON_CARD_START';
export const CREATE_LESSON_CARD_SUCCESS = 'CREATE_LESSON_CARD_SUCCESS';
export const HANDLE_LESSON_CARD_START = 'HANDLE_LESSON_CARD_START';
export const UPDATE_LESSON_CARD_START = 'UPDATE_LESSON_CARD_START';
export const UPDATE_LESSON_CARD_SUCCESS = 'UPDATE_LESSON_CARD_SUCCESS';
export const DELETE_LESSON_CARD_START = 'DELETE_LESSON_CARD_START';
export const DELETE_LESSON_CARD_SUCCESS = 'DELETE_LESSON_CARD_SUCCESS';
export const SELECT_LESSON_CARD_SUCCESS = 'SELECT_LESSON_CARD_SUCCESS';
export const GET_LESSONS_CARDS_START = 'GET_LESSONS_CARDS_START';
export const SET_LESSONS_CARDS_START = 'SET_LESSONS_CARDS_START';
export const GET_LESSON_TYPES_START = 'GET_LESSON_TYPES_START';
export const SET_LESSON_TYPES_SUCCESS = 'SET_LESSON_TYPES_SUCCESS';
export const COPY_LESSON_START = 'COPY_LESSON_START';
export const GET_LESSONS_BY_TEACHER_START = 'GET_LESSONS_BY_TEACHER_START';
export const GET_LESSONS_BY_TEACHER_SUCCESS = 'GET_LESSONS_BY_TEACHER_SUCCESS';
export const UPDATE_LESSON_LINK_START = 'UPDATE_LESSON_LINK_START';
export const UPDATE_LESSON_LINK_SUCCESS = 'UPDATE_LESSON_LINK_SUCCESS';
export const UPDATE_LESSONS_LINK_START = 'UPDATE_LESSONS_LINK_START';
export const UPDATE_LESSONS_LINK_SUCCESS = 'UPDATE_LESSONS_LINK_SUCCESS';
export const CLEAR_TEACHER_LESSONS = 'CLEAR_TEACHER_LESSONS';
export const SET_TEACHER_LESSONS_LOADING = 'SET_TEACHER_LESSONS_LOADING';
export const GET_MY_LESSONS_START = 'GET_MY_LESSONS_START';

// Classes
export const GET_CLASS_SCHEDULE_LIST_START = 'GET_CLASS_SCHEDULE_LIST_START';
export const GET_CLASS_SCHEDULE_LIST_SUCCESS = 'GET_CLASS_SCHEDULE_LIST_SUCCESS';
export const GET_PUBLIC_CLASS_SCHEDULE_LIST_START = 'GET_PUBLIC_CLASS_SCHEDULE_LIST_START';
export const GET_PUBLIC_CLASS_SCHEDULE_LIST_SUCCESS = 'GET_PUBLIC_CLASS_SCHEDULE_LIST_SUCCESS';

// Schedules
export const GET_SCHEDULE_ITEMS_START = 'GET_SCHEDULE_ITEMS_START';
export const GET_SCHEDULE_ITEMS_SUCCESS = 'GET_SCHEDULE_ITEMS_SUCCESS';
export const GET_FULL_SCHEDULE_START = 'GET_FULL_SCHEDULE_START';
export const GET_FULL_SCHEDULE_SUCCESS = 'GET_FULL_SCHEDULE_SUCCESS';
export const GET_GROUP_SCHEDULE_START = 'GET_GROUP_SCHEDULE_START';
export const GET_GROUP_SCHEDULE_SUCCESS = 'GET_GROUP_SCHEDULE_SUCCESS';
export const GET_TEACHER_SCHEDULE_START = 'GET_TEACHER_SCHEDULE_START';
export const GET_TEACHER_SCHEDULE_SUCCESS = 'GET_TEACHER_SCHEDULE_SUCCESS';
export const GET_TEACHER_ACTIVE_SEMESTERS_SCHEDULE_START = 'GET_TEACHER_ACTIVE_SEMESTERS_SCHEDULE_START';
export const GET_TEACHER_RANGE_SCHEDULE_START = 'GET_TEACHER_RANGE_SCHEDULE_START';
export const GET_TEACHER_RANGE_SCHEDULE_SUCCESS = 'GET_TEACHER_RANGE_SCHEDULE_SUCCESS';
export const GET_ALL_SCHEDULE_ITEMS_START = 'GET_ALL_SCHEDULE_ITEMS_START';
export const GET_ALL_PUBLIC_SEMESTERS_START = 'GET_ALL_PUBLIC_SEMESTERS_START';
export const GET_ALL_PUBLIC_SEMESTERS_SUCCESS = 'GET_ALL_PUBLIC_SEMESTERS_SUCCESS';
export const GET_ALL_PUBLIC_GROUPS_START = 'GET_ALL_PUBLIC_GROUPS_START';
export const GET_CURRENT_SEMESTER_START = 'GET_CURRENT_SEMESTER_START';
export const GET_CURRENT_SEMESTER_SUCCESS = 'GET_CURRENT_SEMESTER_SUCCESS';
export const GET_DEFAULT_SEMESTER_START = 'GET_DEFAULT_SEMESTER_START';
export const GET_DEFAULT_SEMESTER_SUCCESS = 'GET_DEFAULT_SEMESTER_SUCCESS';
export const ADD_ITEM_TO_SCHEDULE = 'ADD_ITEM_TO_SCHEDULE';
export const ADD_ITEM_TO_SCHEDULE_START = 'ADD_ITEM_TO_SCHEDULE_START';
export const EDIT_ITEM_TO_SCHEDULE_START = 'EDIT_ITEM_TO_SCHEDULE_START';
export const DELETE_SCHEDULE_ITEM_START = 'DELETE_SCHEDULE_ITEM_START';
export const DELETE_SCHEDULE_ITEM_SUCCESS = 'DELETE_SCHEDULE_ITEM_SUCCESS';
export const DELETE_ITEM_FROM_SCHEDULE = 'DELETE_ITEM_FROM_SCHEDULE';
export const UPDATE_SCHEDULE_ITEM_SUCCESS = 'UPDATE_SCHEDULE_ITEM_SUCCESS';
export const CLEAR_SCHEDULE_START = 'CLEAR_SCHEDULE_START';
export const CHECK_AVAILABILITY_SCHEDULE_START = 'CHECK_AVAILABILITY_SCHEDULE_START';
export const CHECK_AVAILABILITY_CHANGE_ROOM_SCHEDULE_START = 'CHECK_AVAILABILITY_CHANGE_ROOM_SCHEDULE_START';
export const CHECK_AVAILABILITY_CHANGE_ROOM_SCHEDULE_SUCCESS = 'CHECK_AVAILABILITY_CHANGE_ROOM_SCHEDULE_SUCCESS';
export const SEND_TEACHER_SCHEDULE_START = 'SEND_TEACHER_SCHEDULE_START';
export const SCHEDULE_NOT_PUBLISHED = 'SCHEDULE_NOT_PUBLISHED';
export const SET_SCHEDULE_OPERATION_LOADING = 'SET_SCHEDULE_OPERATION_LOADING';
export const SET_SCHEDULE_LOADING_INDICATOR = 'SET_SCHEDULE_LOADING_INDICATOR';
export const SET_MAIN_SCHEDULE_LOADING_INDICATOR = 'SET_MAIN_SCHEDULE_LOADING_INDICATOR';
export const SET_SCHEDULE_TYPE = 'SET_SCHEDULE_TYPE';
export const SET_SCHEDULE_GROUP = 'SET_SCHEDULE_GROUP';
export const SET_SCHEDULE_GROUPS = 'SET_SCHEDULE_GROUPS';
export const SET_SCHEDULE_TEACHER = 'SET_SCHEDULE_TEACHER';
export const SET_SCHEDULE_SEMESTER = 'SET_SCHEDULE_SEMESTER';
export const SET_SCHEDULE_DEPARTMENT = 'SET_SCHEDULE_DEPARTMENT';
export const SET_ITEM_GROUP_ID = 'SET_ITEM_GROUP_ID';
export const SET_PLACE = 'SET_PLACE';
export const SELECT_GROUP_SCHEDULE_START = 'SELECT_GROUP_SCHEDULE_START';
export const SELECT_TEACHER_SCHEDULE_START = 'SELECT_TEACHER_SCHEDULE_START';
export const SELECT_FULL_SCHEDULE_START = 'SELECT_FULL_SCHEDULE_START';
export const SELECT_DEPARTMENT_SCHEDULE_START = 'SELECT_DEPARTMENT_SCHEDULE_START';
export const SET_SCHEDULE_PUBLISHED = 'SET_SCHEDULE_PUBLISHED';

// Temporary Schedules
export const SET_TEMPORARY_SCHEDULES = 'SET_TEMPORARY_SCHEDULES';
export const SET_SCHEDULES_AND_TEMPORARY_SCHEDULES = 'SET_SCHEDULES_AND_TEMPORARY_SCHEDULES';
export const SELECT_TEMPORARY_SCHEDULE = 'SELECT_TEMPORARY_SCHEDULE';
export const SELECT_VACATION = 'SELECT_VACATION';

// UI
export const SET_LOADING_INDICATOR = 'SET_LOADING_INDICATOR';
export const SET_OPEN_SNACKBAR = 'SET_OPEN_SNACKBAR';
export const SET_UNIQUE_ERROR = 'SET_UNIQUE_ERROR';
export const SET_ERROR = 'SET_ERROR';
export const SET_IS_OPEN_CONFIRM_DIALOG = 'SET_IS_OPEN_CONFIRM_DIALOG';
