export const CREATE_LESSON_CARD_SUCCESS = 'CREATE_LESSON_CARD_SUCCESS';
export const CREATE_LESSON_CARD_START = 'CREATE_LESSON_CARD_START';
export const HANDLE_LESSON_CARD_START = 'HANDLE_LESSON_CARD_START';

export const GET_LESSONS_CARDS_START = 'GET_LESSONS_CARDS_START';
export const SET_LESSONS_CARDS = 'SET_LESSONS_CARDS';
export const GET_LESSON_TYPES_START = 'GET_LESSON_TYPES_START';
export const SET_LESSON_TYPES = 'SET_LESSON_TYPES';
export const COPY_LESSON_START = 'COPY_LESSON_START';

export const DELETE_LESSON_CARD_START = 'DELETE_LESSON_CARD_START';
export const DELETE_LESSON_CARD_SUCCESS = 'DELETE_LESSON_CARD_SUCCESS';

export const SELECT_LESSON_CARD = 'SELECT_LESSON_CARD';
export const UPDATE_LESSON_CARD_SUCCESS = 'UPDATE_LESSON_CARD_SUCCESS';
export const UPDATE_LESSON_CARD_START = 'UPDATE_LESSON_CARD_START';

export const SELECT_GROUP_ID = 'SELECT_GROUP_ID';
export const SET_UNIQUE_ERROR = 'SET_UNIQUE_ERROR';

export const SET_TEMPORARY_SCHEDULES = 'SET_TEMPORARY_SCHEDULES';
export const SET_SCHEDULES_AND_TEMPORARY_SCHEDULES = 'SET_SCHEDULES_AND_TEMPORARY_SCHEDULES';
export const SELECT_TEMPORARY_SCHEDULE = 'SELECT_TEMPORARY_SCHEDULE';
export const SELECT_VACATION = 'SELECT_VACATION';
export const SELECT_TEACHER_ID = 'SELECT_TEACHER_ID';

export const SET_OPEN_SNACKBAR = 'SET_OPEN_SNACKBAR';

export const SET_USERS = 'SET_USERS';
export const SET_USER = 'SET_USER';

export const AUTH_USER = 'AUTH_USER';
export const AUTH_USER_SUCCESS = 'AUTH_USER_SUCCESS';
export const AUTH_USER_ERROR = 'AUTH_USER_ERROR';
export const AUTH_USER_INITIATE_LOGOUT = 'AUTH_USER_INITIATE_LOGOUT';
export const AUTH_USER_LOGOUT = 'AUTH_USER_LOGOUT';
export const AUTH_USER_AUTO_LOGOUT = 'AUTH_USER_AUTO_LOGOUT';
export const AUTH_USER_CHECK_STATE = 'AUTH_USER_CHECK_STATE';
export const SET_AUTH_ERROR = 'SET_AUTH_ERROR';

export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR';

export const RESET_USER_PASSWORD = 'RESET_USER_PASSWORD';
export const RESET_USER_PASSWORD_SUCCESS = 'RESET_USER_PASSWORD_SUCCESS';
export const RESET_USER_PASSWORD_ERROR = 'RESET_USER_PASSWORD_ERROR';

export const ACTIVATE_USER = 'ACTIVATE_USER';
export const ACTIVATE_USER_SUCCESS = 'ACTIVATE_USER_SUCCESS';
export const ACTIVATE_USER_ERROR = 'ACTIVATE_USER_ERROR';

export const SET_LOADING_INDICATOR = 'SET_LOADING_INDICATOR';
export const SET_SCHEDULE_LOADING_INDICATOR = 'SET_SCHEDULE_LOADING_INDICATOR';
export const SET_MAIN_SCHEDULE_LOADING_INDICATOR = 'SET_MAIN_SCHEDULE_LOADING_INDICATOR';
export const SET_SEMESTER_LOADING_INDICATOR = 'SET_SEMESTER_LOADING_INDICATOR';

export const SET_SCHEDULE_ITEMS = 'SET_SCHEDULE_ITEMS';
export const GET_SCHEDULE_ITEMS_START = 'GET_SCHEDULE_ITEMS_START';
export const CHECK_AVAILABILITY_CHANGE_ROOM_SCHEDULE_START =
    'CHECK_AVAILABILITY_CHANGE_ROOM_SCHEDULE_START';
export const SET_CURRENT_SEMESTER = 'SET_CURRENT_SEMESTER';
export const GET_CURRENT_SEMESTER_START = 'GET_CURRENT_SEMESTER_START';
export const GET_ALL_PUBLIC_TEACHERS_START = 'GET_ALL_PUBLIC_TEACHERS_START';
export const GET_ALL_PUBLIC_SEMESTERS_START = 'GET_ALL_PUBLIC_SEMESTERS_START';
export const GET_ALL_SCHEDULE_ITEMS_START = 'GET_ALL_SCHEDULE_ITEMS_START';
export const GET_ALL_PUBLIC_GROUPS_START = 'GET_ALL_PUBLIC_GROUPS_START';
export const SEND_TEACHER_SCHEDULE_START = 'SEND_TEACHER_SCHEDULE_START';
export const GET_TEACHER_RANGE_SCHEDULE_START = 'GET_TEACHER_RANGE_SCHEDULE_START';
export const SET_DEFAULT_SEMESTER = 'SET_DEFAULT_SEMESTER';
export const GET_DEFAULT_SEMESTER_START = 'GET_DEFAULT_SEMESTER_START';
export const ADD_ITEM_TO_SCHEDULE = 'ADD_ITEM_TO_SCHEDULE';
export const ADD_ITEM_TO_SCHEDULE_START = 'ADD_ITEM_TO_SCHEDULE_START';
export const EDIT_ITEM_TO_SCHEDULE_START = 'EDIT_ITEM_TO_SCHEDULE_START';
export const DELETE_SCHEDULE_ITEM_START = 'DELETE_SCHEDULE_ITEM_START';
export const CLEAR_SCHEDULE_START = 'CLEAR_SCHEDULE_START';
export const CHECK_AVAILABILITY_SCHEDULE = 'CHECK_AVAILABILITY_SCHEDULE';
export const CHECK_AVAILABILITY_SCHEDULE_START = 'CHECK_AVAILABILITY_SCHEDULE_START';
export const SET_FULL_SCHEDULE = 'SET_FULL_SCHEDULE';
export const SET_GROUP_SCHEDULE = 'SET_GROUP_SCHEDULE';
export const GET_GROUP_SCHEDULE_START = 'GET_GROUP_SCHEDULE_START';
export const GET_TEACHER_SCHEDULE_START = 'GET_TEACHER_SCHEDULE_START';
export const GET_FULL_SCHEDULE_START = 'GET_FULL_SCHEDULE_START';
export const SET_SCHEDULE_TYPE = 'SET_SCHEDULE_TYPE';
export const DELETE_ITEM_FROM_SCHEDULE = 'DELETE_ITEM_FROM_SCHEDULE';
export const SET_ITEM_GROUP_ID = 'SET_ITEM_GROUP_ID';
export const GET_ALL_PUBLIC_TEACHERS_BY_DEPARTMENT_START =
    'GET_ALL_PUBLIC_TEACHERS_BY_DEPARTMENT_START';

export const ADD_TEACHER = 'ADD_TEACHER';
export const SELECT_TEACHER = 'SELECT_TEACHER';
export const SET_TEACHER = 'SET_TEACHER';
export const UPDATE_TEACHER = 'UPDATE_TEACHER';
export const DELETE_TEACHER = 'DELETE_TEACHER';
export const SHOW_ALL = 'SHOW_ALL';
export const GET_TEACHERS_BY_DEPARTMENT = 'GET_TEACHERS_BY_DEPARTMENT';

export const SHOW_ALL_BUSY_ROOMS = 'SHOW_ALL_BUSY_ROOMS';

export const SET_CLASS_SCHEDULE_LIST = 'SET_CLASS_SCHEDULE_LIST';
export const ADD_CLASS_SCHEDULE_ONE = 'ADD_CLASS_SCHEDULE_ONE';
export const GET_CLASS_SCHEDULE_LIST = 'GET_CLASS_SCHEDULE_LIST';
export const GET_CLASS_SCHEDULE_ONE = 'GET_CLASS_SCHEDULE_ONE';
export const DELETE_CLASS_SCHEDULE_ONE = 'DELETE_CLASS_SCHEDULE_ONE';
export const UPDATE_CLASS_SCHEDULE_ONE = 'UPDATE_CLASS_SCHEDULE_ONE';
export const CLEAR_CLASS_SCHEDULE_ONE = 'CLEAR_CLASS_SCHEDULE_ONE';

export const ADD_ROOM = 'ADD_ROOM';
export const DELETE_ROOM = 'DELETE_ROOM';
export const SHOW_LIST_OF_ROOMS = 'SHOW_LIST_OF_ROOMS';
export const SELECT_ONE_ROOM = 'SELECT_ONE_ROOM';
export const UPDATE_ONE_ROOM = 'UPDATE_ONE_ROOM';
export const CLEAR_ROOM_ONE = 'CLEAR_ROOM_ONE';
export const GET_ALL_ROOM_TYPES = 'GET_ALL_ROOM_TYPES';
export const POST_NEW_TYPE = 'POST_NEW_TYPE';
export const DELETE_TYPE = 'DELETE_TYPE';
export const GET_ONE_NEW_TYPE = 'GET_ONE_NEW_TYPE';
export const UPDATE_ONE_TYPE = 'UPDATE_ONE_TYPE';
export const CLEAR_ONE_NEW_TYPE = 'CLEAR_ONE_NEW_TYPE';
export const SHOW_FREE_ROOMS = 'SHOW_FREE_ROOMS';
export const CLEAR_FREE_ROOM = 'CLEAR_FREE_ROOM';

export const ADD_SUBJECT = 'ADD_SUBJECT';
export const DELETE_SUBJECT = 'DELETE_SUBJECT';
export const SHOW_ALL_SUBJECTS = 'SHOW_ALL_SUBJECT';
export const SELECT_SUBJECT = 'SELECT_SUBJECT';
export const UPDATE_SUBJECT = 'UPDATE_SUBJECT';
export const CLEAR_SUBJECT = 'CLEAR_SUBJECT';

export const ADD_DEPARTMENT = 'ADD_DEPARTMENT';
export const GET_ALL_DEPARTMENTS = 'GET_ALL_DEPARTMENTS';
export const CLEAR_DEPARTMENT_FORM = 'CLEAR_DEPARTMENT_FORM';
export const DELETE_DEPARTMENT = 'DELETE_DEPARTMENT';
export const GET_DISABLED_DEPARTMENTS = 'GET_DISABLED_DEPARTMENTS';
export const SET_DISABLED_DEPARTMENT = 'SET_DISABLED_DEPARTMENT';
export const SET_ENABLED_DEPARTMENT = 'SET_ENABLED_DEPARTMENT';
export const GET_DEPARTMENT_BY_ID = 'GET_DEPARTMENT_BY_ID';
export const UPDATE_DEPARTMENT = 'UPDATE_DEPARTMENT';

export const SET_SCHEDULE_GROUP_ID = 'SET_SCHEDULE_GROUP_ID';

export const ADD_SEMESTER = 'ADD_SEMESTER';
export const ADD_SEMESTER_START = 'ADD_SEMESTER_START';
export const DELETE_SEMESTER = 'DELETE_SEMESTER';
export const DELETE_SEMESTER_START = 'DELETE_SEMESTER_START';
export const SHOW_ALL_SEMESTERS = 'SHOW_ALL_SEMESTER';
export const GET_ALL_SEMESTERS_START = 'GET_ALL_SEMESTER_START';
export const SELECT_SEMESTER = 'SELECT_SEMESTER';
export const UPDATE_SEMESTER = 'UPDATE_SEMESTER';
export const UPDATE_SEMESTER_START = 'UPDATE_SEMESTER_START';
export const UPDATE_SEMESTER_BY_ID_START = 'UPDATE_SEMESTER_BY_ID_START';
export const SET_SEMESTER_COPY_START = 'SEMESTER_COPY_START';
export const COPY_LESSONS_FROM_SEMESTER_START = 'COPY_LESSONS_FROM_SEMESTER_START';
export const CLEAR_SEMESTER = 'CLEAR_SEMESTER';
export const SET_ERROR = 'SET_ERROR';
export const SET_ARCHIVED_SEMESTERS = 'SET_ARCHIVED_SEMESTERS';
export const SET_ARCHIVED_SEMESTERS_START = 'SET_ARCHIVED_SEMESTERS_START';
export const GET_ARCHIVE_SEMESTER_START = 'GET_ARCHIVE_SEMESTER_START';
export const CREATE_ARCHIVE_SEMESTER_START = 'CREATE_ARCHIVE_SEMESTER_START';
export const SET_GROUPS_TO_SEMESTER_START = 'SET_GROUPS_TO_SEMESTER_START';

export const SET_DISABLED_ROOMS = 'SET_DISABLED_ROOMS';
export const SET_DISABLED_TEACHERS = 'SET_DISABLED_TEACHERS';
export const SET_DISABLED_GROUPS = 'SET_DISABLED_GROUPS';
export const SET_DISABLED_SEMESTERS = 'SET_DISABLED_SEMESTERS';
export const GET_DISABLED_SEMESTERS_START = 'GET_DISABLED_SEMESTERS_START';
export const SET_DISABLED_SUBJECTS = 'SET_DISABLED_SUBJECTS';

export const SET_SCHEDULE_TEACHER_ID = 'SET_SCHEDULE_TEACHER_ID';
export const SET_TEACHER_SCHEDULE = 'SET_TEACHER_SCHEDULE';
export const SET_SEMESTER_LIST = 'SET_SEMESTER_LIST';
export const SET_SCHEDULE_SEMESTER_ID = 'SET_SCHEDULE_SEMESTER_ID';
export const SET_TEACHER_RANGE_SCHEDULE = 'SET_TEACHER_RANGE_SCHEDULE';
export const SET_TEACHER_VIEW_TYPE = 'SET_TEACHER_VIEW_TYPE';
export const MOVE_SEMESTER_TO_ARCHIVE = 'MOVE_SEMESTER_TO_ARCHIVE';

export const SET_IS_OPEN_CONFIRM_DIALOG = 'SET_IS_OPEN_CONFIRM_DIALOG';
export const SHOW_ALL_GROUPS = 'SHOW_ALL_GROUPS';
export const DELETE_GROUP = 'DELETE_GROUP';
export const SELECT_GROUP = 'SELECT_GROUP';
export const UPDATE_GROUP = 'UPDATE_GROUP';
export const CLEAR_GROUP = 'CLEAR_GROUP';
export const ADD_GROUP = 'ADD_GROUP';

export const TOGGLE_DISABLED_STATUS_GROUP = 'TOGGLE_DISABLED_STATUS_GROUP';
export const FETCH_DISABLED_GROUPS_START = 'FETCH_DISABLED_GROUPS_START';
export const FETCH_ENABLED_GROUPS_START = 'FETCH_ENABLED_GROUPS_START';
export const DELETE_GROUP_START = 'DELETE_GROUP_START';
export const CREATE_GROUP_START = 'CREATE_GROUP_START';
export const UPDATE_GROUP_START = 'UPDATE_GROUP_START';
export const CLEAR_GROUP_START = 'CLEAR_GROUP_START';

export const SHOW_ALL_STUDENTS_BY_GROUP_ID = 'SHOW_ALL_STUDENTS_BY_GROUP_ID';
export const SHOW_ALL_STUDENTS = 'SHOW_ALL_STUDENTS';
export const DELETE_STUDENT = 'DELETE_STUDENT';
export const UPDATE_STUDENT = 'UPDATE_STUDENT';
export const CREATE_STUDENT = 'CREATE_STUDENT';
export const SET_STUDENT = 'SET_STUDENT';

export const START_CREATE_STUDENTS = 'START_CREATE_STUDENTS';
export const START_UPDATE_STUDENTS = 'START_UPDATE_STUDENTS';
export const START_DELETE_STUDENTS = 'START_DELETE_STUDENTS';
export const FETCH_ALL_STUDENTS = 'FETCH_ALL_STUDENTS';
